[project]
name = "supabase-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.4",
    "python-dotenv>=1.2.1",
    "supabase>=2.23.0",
    "uvicorn>=0.38.0",
]
